################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (11.3.rel1)
################################################################################

C++M_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
CCM_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
C_SRCS := 
CXXM_SRCS := 
CYCLO_FILES := 
OBJDUMP_LIST := 
CCM_DEPS := 
C_UPPER_DEPS := 
S_DEPS := 
CXXM_DEPS := 
C_DEPS := 
CC_DEPS := 
SIZE_OUTPUT := 
C++_DEPS := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
CXX_DEPS := 
MAP_FILES := 
S_UPPER_DEPS := 
C++M_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Src/FLASH \
Core/Src/LCD \
Core/Src \
Core/Startup \
Drivers/STM32F4xx_HAL_Driver/Src \
TouchGFX/App \
TouchGFX/build/MINGW32_NT-6.2/generated/fonts/src \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/common \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/dry_setup_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/error_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/home_dry_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/home_reflow_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/menu_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/reflow_setup_edit_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/reflow_setup_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/settings_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/setup_pid_d_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/setup_pid_i_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/setup_pid_p_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/startup_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/images/src \
TouchGFX/build/MINGW32_NT-6.2/generated/images/src/__generated \
TouchGFX/build/MINGW32_NT-6.2/generated/simulator/src \
TouchGFX/build/MINGW32_NT-6.2/generated/simulator/src/video \
TouchGFX/build/MINGW32_NT-6.2/generated/texts/src \
TouchGFX/build/MINGW32_NT-6.2/gui/src/common \
TouchGFX/build/MINGW32_NT-6.2/gui/src/dry_setup_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/error_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/home_dry_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/home_reflow_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/menu_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/model \
TouchGFX/build/MINGW32_NT-6.2/gui/src/reflow_setup_edit_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/reflow_setup_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/settings_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/setup_pid_d_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/setup_pid_i_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/setup_pid_p_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/startup_screen \
TouchGFX/build/MINGW32_NT-6.2/simulator \
TouchGFX/build/MINGW32_NT-6.2/touchgfx/framework/source/platform/driver/touch \
TouchGFX/build/MINGW32_NT-6.2/touchgfx/framework/source/platform/hal/simulator/sdl2 \
TouchGFX/generated/fonts/src \
TouchGFX/generated/gui_generated/src/common \
TouchGFX/generated/gui_generated/src/dry_setup_screen \
TouchGFX/generated/gui_generated/src/error_screen \
TouchGFX/generated/gui_generated/src/home_dry_screen \
TouchGFX/generated/gui_generated/src/home_reflow_screen \
TouchGFX/generated/gui_generated/src/menu_screen \
TouchGFX/generated/gui_generated/src/reflow_setup_edit_screen \
TouchGFX/generated/gui_generated/src/reflow_setup_screen \
TouchGFX/generated/gui_generated/src/settings_screen \
TouchGFX/generated/gui_generated/src/setup_pid_screen \
TouchGFX/generated/gui_generated/src/startup_screen \
TouchGFX/generated/images/src \
TouchGFX/generated/images/src/__generated \
TouchGFX/generated/texts/src \
TouchGFX/gui/src/common \
TouchGFX/gui/src/dry_setup_screen \
TouchGFX/gui/src/error_screen \
TouchGFX/gui/src/home_dry_screen \
TouchGFX/gui/src/home_reflow_screen \
TouchGFX/gui/src/menu_screen \
TouchGFX/gui/src/model \
TouchGFX/gui/src/reflow_setup_edit_screen \
TouchGFX/gui/src/reflow_setup_screen \
TouchGFX/gui/src/settings_screen \
TouchGFX/gui/src/setup_pid_screen \
TouchGFX/gui/src/startup_screen \
TouchGFX/target \
TouchGFX/target/generated \

